# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d9f73260f810d7d90bac7ddd1f7c94afa2d2d6fb2bdc9f085fd011a59ef401261faa5ff09ab99cac4add7d81523c5ec5e703d2177c2bed1d9ad964ade6c3567
  facebook:
    api_key: 144560372344782
    secret: 57805c947f11e77f102fe93c19012326
  twitter:
    api_key: qwcikdIgjkcYjIcUC6kfVl5Vj
    secret: 3TqvoCsEMACwjCAbMto6eaEMftqeP2pqKQzCcPg6YNgrwYegF4
  google_storage:
    access_key: GOOGKCXVBCOBLBXUVJ3N
    secret: nwzJuJGMzhoN71YZyazIoQNOBV+XeoPk/uYziidi

test:
  secret_key_base: be6d5a9d386c914a76567ace14e2898e1fbee329133669ab50b3d7d1105b601cfe8d5de4c420918f0046f4ef7f7efbcc85775e5459748597cc4e4eb1a0615c77
  facebook:
    api_key: 144560372344782
    secret: 57805c947f11e77f102fe93c19012326
  twitter:
    api_key: qwcikdIgjkcYjIcUC6kfVl5Vj
    secret: 3TqvoCsEMACwjCAbMto6eaEMftqeP2pqKQzCcPg6YNgrwYegF4
  google_storage:
    access_key: "accces_key"
    secret: "secret"

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook:
    api_key: <%= ENV["FACEBOOK_API_KEY"] %>
    secret: <%= ENV["FACEBOOK_SECRET"] %>
  twitter:
    api_key: <%= ENV["TWITTER_API_KEY"] %>
    secret: <%= ENV["TWITTER_SECRET"] %>
  google_storage:
    access_key: <%= ENV["GOOGLE_STORAGE_ACCESS_KEY"] %>
    secret: <%= ENV["GOOGLE_STORAGE_SECRET"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook:
    api_key: <%= ENV["FACEBOOK_API_KEY"] %>
    secret: <%= ENV["FACEBOOK_SECRET"] %>
  twitter:
    api_key: <%= ENV["TWITTER_API_KEY"] %>
    secret: <%= ENV["TWITTER_SECRET"] %>
  google_storage:
    access_key: <%= ENV["GOOGLE_STORAGE_ACCESS_KEY"] %>
    secret: <%= ENV["GOOGLE_STORAGE_SECRET"] %>
